-- Litha Life Sciences product impurity catalog.
-- Run this in the Supabase SQL editor before connecting the website.

create table if not exists public.product_impurities (
  id bigint generated by default as identity primary key,
  sl_no integer not null unique,
  api_name text not null,
  impurity_name text,
  cat_no text,
  cas_no text,
  iupac text,
  mf text,
  mw numeric(12, 4),
  storage text,
  inv_status text,
  synonyms text,
  structure text,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists product_impurities_api_name_idx
  on public.product_impurities using gin (to_tsvector('english', api_name));

create index if not exists product_impurities_search_idx
  on public.product_impurities using gin (
    to_tsvector(
      'english',
      coalesce(api_name, '') || ' ' ||
      coalesce(impurity_name, '') || ' ' ||
      coalesce(cat_no, '') || ' ' ||
      coalesce(cas_no, '') || ' ' ||
      coalesce(iupac, '') || ' ' ||
      coalesce(mf, '') || ' ' ||
      coalesce(synonyms, '')
    )
  );

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_product_impurities_updated_at on public.product_impurities;

create trigger set_product_impurities_updated_at
before update on public.product_impurities
for each row
execute function public.set_updated_at();

alter table public.product_impurities enable row level security;

drop policy if exists "Anyone can read product impurity catalog" on public.product_impurities;

create policy "Anyone can read product impurity catalog"
on public.product_impurities
for select
using (true);
